//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/BowlingInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BowlingInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BowlingInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BowlingInputActions"",
    ""maps"": [
        {
            ""name"": ""Slingshot"",
            ""id"": ""9d8daa24-7e7b-4b49-9d05-3d192221acbf"",
            ""actions"": [
                {
                    ""name"": ""Throw"",
                    ""type"": ""Value"",
                    ""id"": ""a74c5f8f-085c-4841-b4c2-9d325b37cc7b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drag"",
                    ""type"": ""Button"",
                    ""id"": ""3036bed5-29ae-4ac0-b2c5-a3cb080f9c71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""4eb872d2-ef84-4644-8438-e8c3b7146cf4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4eec059b-4a13-4c0f-968a-1437547df029"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17733544-63fd-4579-8686-ea9be72c0bf1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1cffdbf-339f-4437-8024-c3f05c89b3ae"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ThreeClick"",
            ""id"": ""c093828c-9d57-44a4-bdc6-70f3fa2ce095"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""9495dd79-cda6-45af-b525-af27b2705c6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9280ef58-c927-415b-b58c-ceec546f8ee7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Slingshot
        m_Slingshot = asset.FindActionMap("Slingshot", throwIfNotFound: true);
        m_Slingshot_Throw = m_Slingshot.FindAction("Throw", throwIfNotFound: true);
        m_Slingshot_Drag = m_Slingshot.FindAction("Drag", throwIfNotFound: true);
        m_Slingshot_Position = m_Slingshot.FindAction("Position", throwIfNotFound: true);
        // ThreeClick
        m_ThreeClick = asset.FindActionMap("ThreeClick", throwIfNotFound: true);
        m_ThreeClick_Click = m_ThreeClick.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Slingshot
    private readonly InputActionMap m_Slingshot;
    private List<ISlingshotActions> m_SlingshotActionsCallbackInterfaces = new List<ISlingshotActions>();
    private readonly InputAction m_Slingshot_Throw;
    private readonly InputAction m_Slingshot_Drag;
    private readonly InputAction m_Slingshot_Position;
    public struct SlingshotActions
    {
        private @BowlingInputActions m_Wrapper;
        public SlingshotActions(@BowlingInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Throw => m_Wrapper.m_Slingshot_Throw;
        public InputAction @Drag => m_Wrapper.m_Slingshot_Drag;
        public InputAction @Position => m_Wrapper.m_Slingshot_Position;
        public InputActionMap Get() { return m_Wrapper.m_Slingshot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SlingshotActions set) { return set.Get(); }
        public void AddCallbacks(ISlingshotActions instance)
        {
            if (instance == null || m_Wrapper.m_SlingshotActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SlingshotActionsCallbackInterfaces.Add(instance);
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @Drag.started += instance.OnDrag;
            @Drag.performed += instance.OnDrag;
            @Drag.canceled += instance.OnDrag;
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
        }

        private void UnregisterCallbacks(ISlingshotActions instance)
        {
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @Drag.started -= instance.OnDrag;
            @Drag.performed -= instance.OnDrag;
            @Drag.canceled -= instance.OnDrag;
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
        }

        public void RemoveCallbacks(ISlingshotActions instance)
        {
            if (m_Wrapper.m_SlingshotActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISlingshotActions instance)
        {
            foreach (var item in m_Wrapper.m_SlingshotActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SlingshotActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SlingshotActions @Slingshot => new SlingshotActions(this);

    // ThreeClick
    private readonly InputActionMap m_ThreeClick;
    private List<IThreeClickActions> m_ThreeClickActionsCallbackInterfaces = new List<IThreeClickActions>();
    private readonly InputAction m_ThreeClick_Click;
    public struct ThreeClickActions
    {
        private @BowlingInputActions m_Wrapper;
        public ThreeClickActions(@BowlingInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_ThreeClick_Click;
        public InputActionMap Get() { return m_Wrapper.m_ThreeClick; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ThreeClickActions set) { return set.Get(); }
        public void AddCallbacks(IThreeClickActions instance)
        {
            if (instance == null || m_Wrapper.m_ThreeClickActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ThreeClickActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IThreeClickActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IThreeClickActions instance)
        {
            if (m_Wrapper.m_ThreeClickActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IThreeClickActions instance)
        {
            foreach (var item in m_Wrapper.m_ThreeClickActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ThreeClickActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ThreeClickActions @ThreeClick => new ThreeClickActions(this);
    public interface ISlingshotActions
    {
        void OnThrow(InputAction.CallbackContext context);
        void OnDrag(InputAction.CallbackContext context);
        void OnPosition(InputAction.CallbackContext context);
    }
    public interface IThreeClickActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
}
